env = Environment()

LIBS =''

common_libs = ['gtest_main', 'gtest', 'pthread']
env.Append( LIBS = common_libs )
env.Append( CPPPATH = ['../'])

env.Program('fetch_test', ['fetch_sm.cpp', 'fetch_test.cpp'], LIBS, LIBPATH='/opt/gtest/lib:/usr/local/lib')
